version: '3'

services:

  mysql-dev:
    image: mysql:8.0.18
    environment:
      MYSQL_ROOT_PASSWORD: devpass
      MYSQL_DATABASE: gray_goose_bar
    ports:
      - "3306:3306"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
  gg-bar:
    image: ggbar:latest
    depends_on:
      - mysql-dev
    environment:
      DATABASE_USER: root
      DATABASE_PASS: devpass
      DATABASE_NAME: gray_goose_bar
      DATABASE_HOST: mysql-dev:3306
      BOT_TOKEN: ${BOT_TOKEN}
      API_LOGIN: ${API_LOGIN}
      API_PASSWORD: ${API_PASSWORD}
      WAIT_HOSTS: mysql-dev:3306
      HTTP_PROXY: ${HTTPS_PROXY}
    ports:
      - "8080:8080"
    links:
      - mysql-dev