[[constraint]]
  name = "github.com/go-telegram-bot-api/telegram-bot-api"
  version = "4.6.4"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.4.1"

[[constraint]]
  branch = "master"
  name = "github.com/streadway/amqp"
